

import { GlobalContent, Language, ServiceData, Car } from './types';

export const CONTENT: GlobalContent = {
  hero: {
    title: {
      [Language.RO]: 'Soluții Auto & Financiare Premium',
      [Language.DE]: 'Premium Auto- & Finanzlösungen',
      [Language.EN]: 'Premium Auto & Financial Solutions',
      [Language.IT]: 'Soluzioni Auto e Finanziarie Premium',
    },
    subtitle: {
      [Language.RO]: 'Partenerul tău de încredere în Germania pentru finanțări, asigurări și servicii auto complete.',
      [Language.DE]: 'Ihr vertrauenswürdiger Partner in Deutschland für Finanzierung, Versicherung und kompletten Autoservice.',
      [Language.EN]: 'Your trusted partner in Germany for financing, insurance, and complete car services.',
      [Language.IT]: 'Il tuo partner di fiducia in Germania per finanziamenti, assicurazioni e servizi auto completi.',
    },
    cta: {
      [Language.RO]: 'Vezi Serviciile',
      [Language.DE]: 'Dienstleistungen ansehen',
      [Language.EN]: 'View Services',
      [Language.IT]: 'Visualizza Servizi',
    },
  },
  stats: [
    {
      value: '7.500+',
      icon: 'Users',
      title: {
        [Language.RO]: 'Clienți mulțumiți',
        [Language.DE]: 'Zufriedene Kunden',
        [Language.EN]: 'Happy Customers',
        [Language.IT]: 'Clienti Felici',
      },
    },
    {
      value: '98%',
      icon: 'ThumbsUp',
      title: {
        [Language.RO]: 'Satisfacție clienți',
        [Language.DE]: 'Kundenzufriedenheit',
        [Language.EN]: 'Customer Satisfaction',
        [Language.IT]: 'Soddisfazione del Cliente',
      },
    },
    {
      value: '24/7',
      icon: 'Clock',
      title: {
        [Language.RO]: 'Suport disponibil',
        [Language.DE]: 'Support verfügbar',
        [Language.EN]: 'Support Available',
        [Language.IT]: 'Supporto Disponibile',
      },
    },
  ],
  carSales: {
    priceCurrency: '€',
    viewDetails: {
      [Language.RO]: 'Detalii Mașină',
      [Language.DE]: 'Fahrzeugdetails',
      [Language.EN]: 'Car Details',
      [Language.IT]: 'Dettagli Auto',
    },
    closeDetails: {
      [Language.RO]: 'Închide',
      [Language.DE]: 'Schließen',
      [Language.EN]: 'Close',
      [Language.IT]: 'Chiudi',
    },
    specs: {
      year: { [Language.RO]: 'An', [Language.DE]: 'Jahr', [Language.EN]: 'Year', [Language.IT]: 'Anno' },
      mileage: { [Language.RO]: 'Km', [Language.DE]: 'Km', [Language.EN]: 'Mileage', [Language.IT]: 'Km' },
      power: { [Language.RO]: 'CP', [Language.DE]: 'PS', [Language.EN]: 'HP', [Language.IT]: 'CV' },
      fuel: { [Language.RO]: 'Combustibil', [Language.DE]: 'Kraftstoff', [Language.EN]: 'Fuel', [Language.IT]: 'Carburante' },
      
      // Detailed Specs Translations
      series: { [Language.RO]: 'Serie Model', [Language.DE]: 'Baureihe', [Language.EN]: 'Model Series', [Language.IT]: 'Serie Modello' },
      trim: { [Language.RO]: 'Echipare', [Language.DE]: 'Ausstattungslinie', [Language.EN]: 'Trim Line', [Language.IT]: 'Allestimento' },
      engineVolume: { [Language.RO]: 'Capacitate Cilindrică', [Language.DE]: 'Hubraum', [Language.EN]: 'Displacement', [Language.IT]: 'Cilindrata' },
      seats: { [Language.RO]: 'Nr. Locuri', [Language.DE]: 'Anzahl Sitzplätze', [Language.EN]: 'Seats', [Language.IT]: 'Posti' },
      doors: { [Language.RO]: 'Nr. Uși', [Language.DE]: 'Anzahl der Türen', [Language.EN]: 'Doors', [Language.IT]: 'Porte' },
      emissionClass: { [Language.RO]: 'Normă Poluare', [Language.DE]: 'Schadstoffklasse', [Language.EN]: 'Emission Class', [Language.IT]: 'Classe Emissioni' },
      inspection: { [Language.RO]: 'ITP', [Language.DE]: 'HU', [Language.EN]: 'Inspection (MOT)', [Language.IT]: 'Revisione' },
      climate: { [Language.RO]: 'Climatizare', [Language.DE]: 'Klimatisierung', [Language.EN]: 'Climate Control', [Language.IT]: 'Climatizzazione' },
      airbags: { [Language.RO]: 'Airbag-uri', [Language.DE]: 'Airbags', [Language.EN]: 'Airbags', [Language.IT]: 'Airbag' },
      colorManuf: { [Language.RO]: 'Culoare (Producător)', [Language.DE]: 'Farbe (Hersteller)', [Language.EN]: 'Color (Manufacturer)', [Language.IT]: 'Colore (Produttore)' },
      color: { [Language.RO]: 'Culoare', [Language.DE]: 'Farbe', [Language.EN]: 'Color', [Language.IT]: 'Colore' },
      interior: { [Language.RO]: 'Interior', [Language.DE]: 'Innenausstattung', [Language.EN]: 'Interior', [Language.IT]: 'Interni' },
      towBraked: { [Language.RO]: 'Remorcare (cu frâne)', [Language.DE]: 'Anhängelast gebremst', [Language.EN]: 'Towing (Braked)', [Language.IT]: 'Traino (frenato)' },
      towUnbraked: { [Language.RO]: 'Remorcare (fără frâne)', [Language.DE]: 'Anhängelast ungebremst', [Language.EN]: 'Towing (Unbraked)', [Language.IT]: 'Traino (non frenato)' },
      weight: { [Language.RO]: 'Greutate', [Language.DE]: 'Gewicht', [Language.EN]: 'Weight', [Language.IT]: 'Peso' },
      cylinders: { [Language.RO]: 'Cilindri', [Language.DE]: 'Zylinder', [Language.EN]: 'Cylinders', [Language.IT]: 'Cilindri' },
      tank: { [Language.RO]: 'Rezervor', [Language.DE]: 'Tankgröße', [Language.EN]: 'Tank Size', [Language.IT]: 'Serbatoio' },
      driveType: { [Language.RO]: 'Tip Motor/Tracțiune', [Language.DE]: 'Antriebsart', [Language.EN]: 'Drive/Engine Type', [Language.IT]: 'Tipo Motore/Trazione' },
      consumption: { [Language.RO]: 'Consum Energie', [Language.DE]: 'Energieverbrauch (komb.)', [Language.EN]: 'Energy Cons.', [Language.IT]: 'Consumo Energia' },
      co2: { [Language.RO]: 'Emisii CO₂', [Language.DE]: 'CO₂-Emissionen', [Language.EN]: 'CO₂ Emissions', [Language.IT]: 'Emissioni CO₂' },
      fuelConsCombined: { [Language.RO]: 'Consum Combustibil', [Language.DE]: 'Kraftstoffverbrauch', [Language.EN]: 'Fuel Consumption', [Language.IT]: 'Consumo Carburante' },
    },
  },
  newsletter: {
    title: {
      [Language.RO]: 'Abonează-te la Newsletter-ul nostru',
      [Language.DE]: 'Abonnieren Sie unseren Newsletter',
      [Language.EN]: 'Subscribe to Our Newsletter',
      [Language.IT]: 'Iscriviti alla Nostra Newsletter',
    },
    subtitle: {
      [Language.RO]: 'Fii la curent cu ultimele noastre știri și oferte!',
      [Language.DE]: 'Bleiben Sie auf dem Laufenden mit unseren neuesten Nachrichten und Angeboten!',
      [Language.EN]: 'Stay updated with our latest news and offers!',
      [Language.IT]: 'Rimani aggiornato con le nostre ultime notizie e offerte!',
    },
    emailPlaceholder: {
      [Language.RO]: 'adresa ta de email...',
      [Language.DE]: 'deine E-Mail-Adresse...',
      [Language.EN]: 'your email address...',
      [Language.IT]: 'il tuo indirizzo email...',
    },
    subscribeButton: {
      [Language.RO]: 'Abonează-te',
      [Language.DE]: 'Abonnieren',
      [Language.EN]: 'Subscribe',
      [Language.IT]: 'Iscriviti',
    },
    subscribingButton: {
      [Language.RO]: 'Abonare...',
      [Language.DE]: 'Abonniere...',
      [Language.EN]: 'Subscribing...',
      [Language.IT]: 'Iscrizione in corso...',
    },
    successMessage: {
      [Language.RO]: 'Abonare reușită! Mulțumim.',
      [Language.DE]: 'Abonnement erfolgreich! Vielen Dank.',
      [Language.EN]: 'Subscription successful! Thank you.',
      [Language.IT]: 'Iscrizione avvenuta con successo! Grazie.',
    },
    failureMessage: {
      [Language.RO]: 'Abonarea a eșuat. Te rugăm să încerci din nou.',
      [Language.DE]: 'Abonnement fehlgeschlagen. Bitte versuchen Sie es erneut.',
      [Language.EN]: 'Subscription failed. Please try again.',
      [Language.IT]: 'Iscrizione fallita. Riprova.',
    },
    errorMessage: {
      [Language.RO]: 'A apărut o eroare. Te rugăm să încerci din nou mai târziu.',
      [Language.DE]: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.',
      [Language.EN]: 'An error occurred. Please try again later.',
      [Language.IT]: 'Si è verificato un errore. Riprova più tardi.',
    },
  },
  footer: {
    rights: {
      [Language.RO]: 'Toate drepturile rezervate.',
      [Language.DE]: 'Alle Rechte vorbehalten.',
      [Language.EN]: 'All rights reserved.',
      [Language.IT]: 'Tutti i diritti riservati.',
    },
    contact: {
      [Language.RO]: 'Contact',
      [Language.DE]: 'Kontakt',
      [Language.EN]: 'Contact',
      [Language.IT]: 'Contatto',
    },
  },
  common: {
    back: {
      [Language.RO]: 'Înapoi',
      [Language.DE]: 'Zurück',
      [Language.EN]: 'Back',
      [Language.IT]: 'Indietro',
    },
    selectPartner: {
      [Language.RO]: 'Alege un Partener',
      [Language.DE]: 'Wählen Sie einen Partner',
      [Language.EN]: 'Select a Partner',
      [Language.IT]: 'Seleziona un Partner',
    },
    contactPartner: {
      [Language.RO]: 'Contactează',
      [Language.DE]: 'Kontaktieren',
      [Language.EN]: 'Contact',
      [Language.IT]: 'Contatta',
    },
    visitWebsite: {
      [Language.RO]: 'Vizitează Site',
      [Language.DE]: 'Webseite besuchen',
      [Language.EN]: 'Visit Website',
      [Language.IT]: 'Visita il Sito',
    },
    callNow: {
      [Language.RO]: 'Suna acum!',
      [Language.DE]: 'Jetzt anrufen!',
      [Language.EN]: 'Call Now!',
      [Language.IT]: 'Chiama ora!',
    },
    details: {
      [Language.RO]: 'Detalii',
      [Language.DE]: 'Details',
      [Language.EN]: 'Details',
      [Language.IT]: 'Dettagli',
    },
  },
};

const tudoseAlexandruFinanz = {
  id: 'tudose-alexandru-finanz',
  name: 'Tudose Alexandru Finanz',
  description: {
    [Language.RO]: 'Partener financiar de încredere.',
    [Language.DE]: 'Vertrauenswürdiger Finanzpartner.',
    [Language.EN]: 'Trusted financial partner.',
    [Language.IT]: 'Partner finanziario di fiducia.',
  },
  phone: '+49 15175312107', // Placeholder, user to provide correct number
  website: '#' // Placeholder, user to provide correct site
};

export const FEATURED_CARS: Car[] = [
  {
    id: 'car-1',
    make: 'Audi',
    model: 'A6 Allroad quattro 45 TDI',
    year: 2020,
    price: 34499,
    mileage: 139000,
    power: 231, // Converted 170 kW to approx PS for display consistency
    fuel: 'Diesel',
    image: '/audia6_1.png', // Audi A6-like image
    images: ['/audia6_1.png',
'/audia6_2.jpg',
'/audia6_3.jpg',
'/audia6_4.jpg',
'/audia6_5.jpg',
'/audia6_6.jpg',
'/audia6_7.jpg',
'/audia6_8.jpg',
'/audia6_9.jpg',
'/audia6_10.jpg',
'/audia6_11.jpg',
'/audia6_12.jpg',
'/audia6_13.jpg',
'/audia6_14.jpg',
'/audia6_15.jpg'],
    details: {
      series: 'A6 Allroad quattro (4AH)(06.2019->)',
      trim: '45 TDI basis',
      engineVolume: '2.967 cm³',
      seats: 5,
      doors: '4/5',
      emissionClass: 'Euro6',
      inspection: {
        [Language.RO]: 'Nou',
        [Language.DE]: 'Neu',
        [Language.EN]: 'New',
        [Language.IT]: 'Nuovo',
      },
      climate: {
        [Language.RO]: 'Climatizare automată 4 zone',
        [Language.DE]: '4-Zonen-Klimaautomatik',
        [Language.EN]: '4-zone automatic climate control',
        [Language.IT]: 'Climatizzatore automatico a 4 zone',
      },
      airbags: {
        [Language.RO]: 'Față, lateral și altele',
        [Language.DE]: 'Front-, Seiten- und weitere Airbags',
        [Language.EN]: 'Front, side and other airbags',
        [Language.IT]: 'Airbag anteriori, laterali e altri',
      },
      colorManuf: 'FIRMAMENTBLAU',
      color: {
        [Language.RO]: 'Albastru Metalizat',
        [Language.DE]: 'Blau Metallic',
        [Language.EN]: 'Blue Metallic',
        [Language.IT]: 'Blu Metallizzato',
      },
      interior: {
        [Language.RO]: 'Alcantara',
        [Language.DE]: 'Alcantara',
        [Language.EN]: 'Alcantara',
        [Language.IT]: 'Alcantara',
      },
      towBraked: '2.500 kg',
      towUnbraked: '750 kg',
      weight: '2.020 kg',
      cylinders: 6,
      tank: '63 l',
      driveType: {
        [Language.RO]: 'Motor cu ardere internă',
        [Language.DE]: 'Verbrennungsmotor',
        [Language.EN]: 'Combustion Engine',
        [Language.IT]: 'Motore a combustione interna',
      },
      consumption: '5,8 l/100km',
      co2: '152 g/km',
      fuelConsCombined: {
        [Language.RO]: '5,8 l/100km (mixt)',
        [Language.DE]: '5,8 l/100km (kombiniert)',
        [Language.EN]: '5.8 l/100km (combined)',
        [Language.IT]: '5,8 l/100km (combinato)',
      },
    }
  },
  {
    id: 'car-2',
    make: 'Audi',
    model: 'A4 Lim. 30 TDI Advanced',
    year: 2020,
    price: 22999,
    mileage: 157000,
    power: 136,
    fuel: 'Diesel',
    image: '/audia4_1.png',
    images: ['/audia4_1.png',
'/audia4_2.jpg',
'/audia4_3.jpg',
'/audia4_4.jpg',
'/audia4_5.jpg',
'/audia4_6.jpg',
'/audia4_7.jpg',
'/audia4_8.jpg',
'/audia4_9.jpg',
'/audia4_10.jpg',
'/audia4_11.jpg',
'/audia4_12.jpg',
'/audia4_13.jpg',
'/audia4_14.jpg',
'/audia4_15.jpg'],
    details: {
      series: 'A4 Lim. (8WC)(05.2019->)',
      trim: '30 TDI advanced',
      engineVolume: '1.968 cm³',
      seats: 5,
      doors: '4/5',
      emissionClass: 'Euro6d-TEMP',
      inspection: {
        [Language.RO]: 'ITP Nou',
        [Language.DE]: 'Neu',
        [Language.EN]: 'New',
        [Language.IT]: 'Nuovo',
      },
      climate: {
        [Language.RO]: 'Climatizare automată',
        [Language.DE]: 'Klimaautomatik',
        [Language.EN]: 'Automatic climate control',
        [Language.IT]: 'Climatizzatore automatico',
      },
      airbags: {
        [Language.RO]: 'Față, lateral și altele',
        [Language.DE]: 'Front-, Seiten- und weitere Airbags',
        [Language.EN]: 'Front, side and other airbags',
        [Language.IT]: 'Airbag anteriori, laterali e altri',
      },
      colorManuf: 'IBISWEISS',
      color: {
        [Language.RO]: 'Alb Metalizat',
        [Language.DE]: 'Weiß Metallic',
        [Language.EN]: 'White Metallic',
        [Language.IT]: 'Bianco Metallizzato',
      },
      interior: {
        [Language.RO]: 'Stofă, Negru',
        [Language.DE]: 'Stoff, Schwarz',
        [Language.EN]: 'Fabric, Black',
        [Language.IT]: 'Tessuto, Nero',
      },
      towBraked: '1.500 kg',
      towUnbraked: '750 kg',
      weight: '1.565 kg',
      cylinders: 4,
      tank: '40 l',
      driveType: {
        [Language.RO]: 'Motor cu ardere internă',
        [Language.DE]: 'Verbrennungsmotor',
        [Language.EN]: 'Combustion Engine',
        [Language.IT]: 'Motore a combustione interna',
      },
      consumption: '4,2 l/100km',
      co2: '109 g/km',
      fuelConsCombined: {
        [Language.RO]: '4,2 l/100km (mixt)',
        [Language.DE]: '4,2 l/100km (kombiniert)',
        [Language.EN]: '4.2 l/100km (combined)',
        [Language.IT]: '4,2 l/100km (combinato)',
      },
    }
  },
  {
    id: 'car-3',
    make: 'BMW',
    model: '520d Limousine',
    year: 2020,
    price: 32999,
    mileage: 151000,
    power: 190,
    fuel: 'Diesel',
    image: '/bmw_1.jpg',
    images: ['/bmw_1.jpg',
'/bmw_2.jpg',
'/bmw_3.jpg',
'/bmw_4.jpg',
'/bmw_5.jpg',
'/bmw_6.jpg',
'/bmw_7.jpg',
'/bmw_8.jpg',
'/bmw_9.jpg',
'/bmw_10.jpg',
'/bmw_11.jpg',
'/bmw_12.jpg',
'/bmw_13.jpg',
'/bmw_14.jpg',
'/bmw_15.jpg'],
    details: {
      series: 'G30',
      trim: '520 d',
      engineVolume: '1.995 cm³',
      seats: 5,
      doors: '4/5',
      emissionClass: 'Euro6d',
      inspection: {
        [Language.RO]: 'ITP Nou',
        [Language.DE]: 'Neu',
        [Language.EN]: 'New',
        [Language.IT]: 'Nuovo',
      },
      climate: {
        [Language.RO]: 'Climatizare automată 4 zone',
        [Language.DE]: '4-Zonen-Klimaautomatik',
        [Language.EN]: '4-zone automatic climate control',
        [Language.IT]: 'Climatizzatore automatico a 4 zone',
      },
      airbags: {
        [Language.RO]: 'Față, lateral și altele',
        [Language.DE]: 'Front-, Seiten- und weitere Airbags',
        [Language.EN]: 'Front, side and other airbags',
        [Language.IT]: 'Airbag anteriori, laterali e altri',
      },
      colorManuf: 'BERNINAGRAU BERNSTEINEFFEKT META',
      color: {
        [Language.RO]: 'Gri Metalizat',
        [Language.DE]: 'Grau Metallic',
        [Language.EN]: 'Grey Metallic',
        [Language.IT]: 'Grigio Metallizzato',
      },
      interior: {
        [Language.RO]: 'Piele integrală, Maro',
        [Language.DE]: 'Vollleder, Braun',
        [Language.EN]: 'Full leather, Brown',
        [Language.IT]: 'Pelle integrale, Marrone',
      },
      towBraked: '2.000 kg',
      towUnbraked: '750 kg',
      weight: '1.750 kg',
      cylinders: 4,
      tank: '66 l',
      driveType: {
        [Language.RO]: 'Motor cu ardere internă',
        [Language.DE]: 'Verbrennungsmotor',
        [Language.EN]: 'Combustion Engine',
        [Language.IT]: 'Motore a combustione interna',
      },
      consumption: '4,3 l/100km',
      co2: '112 g/km',
      fuelConsCombined: {
        [Language.RO]: '4,3 l/100km (mixt)',
        [Language.DE]: '4,3 l/100km (kombiniert)',
        [Language.EN]: '4.3 l/100km (combined)',
        [Language.IT]: '4,3 l/100km (combinato)',
      },
    }
  },
  {
    id: 'car-4',
    make: 'Mercedes-Benz',
    model: 'C 220 C -Klasse Lim. C 220 d',
    year: 2021,
    price: 29999,
    mileage: 106000,
    power: 194,
    fuel: 'Diesel',
    image: '/mercedes_1.png',
    images: ['/mercedes_1.png',
'/mercedes_2.jpg',
'/mercedes_3.jpg',
'/mercedes_4.jpg',
'/mercedes_5.jpg',
'/mercedes_6.jpg',
'/mercedes_7.jpg',
'/mercedes_8.jpg',
'/mercedes_9.jpg',
'/mercedes_10.jpg',
'/mercedes_11.jpg',
'/mercedes_12.jpg',
'/mercedes_13.jpg',
'/mercedes_14.jpg',
'/mercedes_15.jpg'],
    details: {
      series: 'C -Klasse Lim. (BM 205)(03.2014->)',
      trim: 'C 220 d (205.014)',
      engineVolume: '1.950 cm³',
      seats: 5,
      doors: '4/5',
      emissionClass: 'Euro6d',
      inspection: {
        [Language.RO]: 'ITP Nou',
        [Language.DE]: 'Neu',
        [Language.EN]: 'New',
        [Language.IT]: 'Nuovo',
      },
      climate: {
        [Language.RO]: 'Climatizare automată',
        [Language.DE]: 'Klimaautomatik',
        [Language.EN]: 'Automatic climate control',
        [Language.IT]: 'Climatizzatore automatico',
      },
      airbags: {
        [Language.RO]: 'Față, lateral și altele',
        [Language.DE]: 'Front-, Seiten- und weitere Airbags',
        [Language.EN]: 'Front, side and other airbags',
        [Language.IT]: 'Airbag anteriori, laterali e altri',
      },
      colorManuf: 'CAVANSITBLAU',
      color: {
        [Language.RO]: 'Albastru Metalizat',
        [Language.DE]: 'Blau Metallic',
        [Language.EN]: 'Blue Metallic',
        [Language.IT]: 'Blu Metallizzato',
      },
      interior: {
        [Language.RO]: 'Piele integrală, Negru',
        [Language.DE]: 'Vollleder, Schwarz',
        [Language.EN]: 'Full leather, Black',
        [Language.IT]: 'Pelle integrale, Nero',
      },
      towBraked: '1.800 kg',
      towUnbraked: '750 kg',
      weight: '1.585 kg',
      cylinders: 4,
      tank: '41 l',
      driveType: {
        [Language.RO]: 'Motor cu ardere internă',
        [Language.DE]: 'Verbrennungsmotor',
        [Language.EN]: 'Combustion Engine',
        [Language.IT]: 'Motore a combustione interna',
      },
      consumption: '4,3 l/100km',
      co2: '113 g/km',
      fuelConsCombined: {
        [Language.RO]: '4,3 l/100km (mixt)',
        [Language.DE]: '4,3 l/100km (kombiniert)',
        [Language.EN]: '4.3 l/100km (combined)',
        [Language.IT]: '4,3 l/100km (combinato)',
      },
    }
  },
  {
    id: 'car-5',
    make: 'Volkswagen',
    model: 'Passat Variant Business',
    year: 2020,
    price: 20999,
    mileage: 127000,
    power: 150,
    fuel: 'Diesel',
    image: '/volskwagenpassat1.png',
    images: [
      '/volskwagenpassat1.png',
      '/volskwagenpassat2.jpg',
      '/volskwagenpassat3.jpg',
      '/volskwagenpassat4.jpg',
      '/volskwagenpassat5.jpg',
      '/volskwagenpassat6.jpg',
      '/volskwagenpassat7.jpg',
      '/volskwagenpassat8.jpg',
      '/volskwagenpassat9.jpg',
      '/volskwagenpassat10.jpg',
      '/volskwagenpassat11.jpg',
      '/volskwagenpassat12.jpg',
      '/volskwagenpassat13.jpg',
      '/volskwagenpassat14.jpg',
      '/volskwagenpassat15.jpg'
    ],
    details: {
      series: 'Passat Variant (CB5)(03.2019->2024)',
      trim: 'Business',
      engineVolume: '1.968 cm³',
      seats: 5,
      doors: '4/5',
      emissionClass: 'Euro6',
      inspection: {
        [Language.RO]: 'ITP Nou',
        [Language.DE]: 'Neu',
        [Language.EN]: 'New',
        [Language.IT]: 'Nuovo',
      },
      climate: {
        [Language.RO]: 'Climatizare automată',
        [Language.DE]: 'Klimaautomatik',
        [Language.EN]: 'Automatic climate control',
        [Language.IT]: 'Climatizzatore automatico',
      },
      airbags: {
        [Language.RO]: 'Față, lateral și altele',
        [Language.DE]: 'Front-, Seiten- und weitere Airbags',
        [Language.EN]: 'Front, side and other airbags',
        [Language.IT]: 'Airbag anteriori, laterali e altri',
      },
      colorManuf: 'Reflexsilber Metallic',
      color: {
        [Language.RO]: 'Argintiu Metalizat',
        [Language.DE]: 'Silber Metallic',
        [Language.EN]: 'Silver Metallic',
        [Language.IT]: 'Argento Metallizzato',
      },
      interior: {
        [Language.RO]: 'Stofă, Negru',
        [Language.DE]: 'Stoff, Schwarz',
        [Language.EN]: 'Fabric, Black',
        [Language.IT]: 'Tessuto, Nero',
      },
      towBraked: '2.000 kg',
      towUnbraked: '750 kg',
      weight: '1.590 kg',
      cylinders: 4,
      tank: '66 l',
      driveType: {
        [Language.RO]: 'Motor cu ardere internă',
        [Language.DE]: 'Verbrennungsmotor',
        [Language.EN]: 'Combustion Engine',
        [Language.IT]: 'Motore a combustione interna',
      },
      consumption: '4,0 l/100km',
      co2: '105 g/km',
      fuelConsCombined: {
        [Language.RO]: '4,0 l/100km (mixt)',
        [Language.DE]: '4,0 l/100km (kombiniert)',
        [Language.EN]: '4.0 l/100km (combined)',
        [Language.IT]: '4,0 l/100km (combinato)',
      },
    }
  },
  {
    id: 'car-6',
    make: 'Volkswagen',
    model: 'Touran Highline BMT Start-Stopp',
    year: 2020,
    price: 25999,
    mileage: 117000,
    power: 150,
    fuel: 'Diesel',
    image: '/volskwagentouran_1.png',
    images: ['/volskwagentouran_1.png',
'/volskwagentouran_2.jpg',
'/volskwagentouran_3.jpg',
'/volskwagentouran_4.jpg',
'/volskwagentouran_5.jpg',
'/volskwagentouran_6.jpg',
'/volskwagentouran_7.jpg',
'/volskwagentouran_8.jpg',
'/volskwagentouran_9.jpg',
'/volskwagentouran_10.jpg',
'/volskwagentouran_11.jpg',
'/volskwagentouran_12.jpg',
'/volskwagentouran_13.jpg',
'/volskwagentouran_14.jpg',
'/volskwagentouran_15.jpg'],
    details: {
      series: 'Touran (5T1)(04.2015->)',
      trim: 'Highline BMT/Start-Stopp',
      engineVolume: '1.968 cm³',
      seats: 7,
      doors: '4/5',
      emissionClass: 'Euro6d-TEMP',
      inspection: {
        [Language.RO]: 'ITP Nou',
        [Language.DE]: 'Neu',
        [Language.EN]: 'New',
        [Language.IT]: 'Nuovo',
      },
      climate: {
        [Language.RO]: 'Climatizare automată 3 zone',
        [Language.DE]: '3-Zonen-Klimaautomatik',
        [Language.EN]: '3-zone automatic climate control',
        [Language.IT]: 'Climatizzatore automatico a 3 zone',
      },
      airbags: {
        [Language.RO]: 'Față, lateral și altele',
        [Language.DE]: 'Front-, Seiten- und weitere Airbags',
        [Language.EN]: 'Front, side and other airbags',
        [Language.IT]: 'Airbag anteriori, laterali e altri',
      },
      colorManuf: 'Indiumgrau Metallic',
      color: {
        [Language.RO]: 'Gri Metalizat',
        [Language.DE]: 'Grau Metallic',
        [Language.EN]: 'Grey Metallic',
        [Language.IT]: 'Grigio Metallizzato',
      },
      interior: {
        [Language.RO]: 'Alcantara, Negru',
        [Language.DE]: 'Alcantara, Schwarz',
        [Language.EN]: 'Alcantara, Black',
        [Language.IT]: 'Alcantara, Nero',
      },
      towBraked: '2.000 kg',
      towUnbraked: '750 kg',
      weight: '1.620 kg',
      cylinders: 4,
      tank: '58 l',
      driveType: {
        [Language.RO]: 'Motor cu ardere internă',
        [Language.DE]: 'Verbrennungsmotor',
        [Language.EN]: 'Combustion Engine',
        [Language.IT]: 'Motore a combustione interna',
      },
      consumption: '4,5 l/100km',
      co2: '119 g/km',
      fuelConsCombined: {
        [Language.RO]: '4,5 l/100km (mixt)',
        [Language.DE]: '4,5 l/100km (kombiniert)',
        [Language.EN]: '4.5 l/100km (combined)',
        [Language.IT]: '4,5 l/100km (combinato)',
      },
    }
  }
];

export const SERVICES: ServiceData[] = [
  {
    id: 'car-sales',
    iconName: 'Car',
    title: { [Language.RO]: 'Vânzări Auto', [Language.DE]: 'Fahrzeugverkauf', [Language.EN]: 'Car Sales', [Language.IT]: 'Vendita Auto' },
    description: { [Language.RO]: 'Autoturisme verificate disponibile pe stoc.', [Language.DE]: 'Geprüfte Fahrzeuge auf Lager verfügbar.', [Language.EN]: 'Verified cars available in stock.', [Language.IT]: 'Auto verificate disponibili in magazzino.' },
    longDescription: { [Language.RO]: 'Descoperiți selecția noastră de autoturisme premium, verificate tehnic și estetic. Oferim garanție, istoric service complet și posibilități de finanțare rapidă pentru fiecare mașină din parcul nostru.', [Language.DE]: 'Entdecken Sie unsere Auswahl an Premium-Fahrzeugen, technisch und optisch geprüft. Wir bieten Garantie, vollständige Servicehistorie und schnelle Finanzierungsmöglichkeiten.', [Language.EN]: 'Discover our selection of premium cars, technically and aesthetically checked. We offer warranty, full service history, and fast financing options for every car in our fleet.', [Language.IT]: 'Scopri la nostra selezione di auto premium, controllate tecnicamente ed esteticamente. Offriamo garanzia, cronologia completa dei servizi e opzioni di finanziamento rapido.' },
    partners: [], // Will render FEATURED_CARS instead
  },
   {
    id: 'car-check',
    iconName: 'Search',
    title: { [Language.RO]: 'Verificari auto', [Language.DE]: 'Fahrzeugüberprüfungen', [Language.EN]: 'Car Checks', [Language.IT]: 'Controlli Auto' },
    description: { [Language.RO]: 'Verificarea tehnică și istorică a mașinii.', [Language.DE]: 'Technische und historische Überprüfung des Autos.', [Language.EN]: 'Technical and historical check of the car.', [Language.IT]: 'Controllo tecnico e storico dell\'auto.' },
    longDescription: { [Language.RO]: 'Servicii complete de verificare auto, inclusiv inspecție tehnică detaliată, verificare istoric daune și verificare kilometraj. Partenerul nostru de încredere vă stă la dispoziție.', [Language.DE]: 'Umfassende Fahrzeugüberprüfungsdienste, einschließlich detaillierter technischer Inspektion, Überprüfung der Schadenshistorie und Kilometerstandsüberprüfung. Unser vertrauenswürdiger Partner steht Ihnen zur Verfügung.', [Language.EN]: 'Comprehensive car check services, including detailed technical inspection, damage history check, and mileage verification. Our trusted partner is at your disposal.', [Language.IT]: 'Servizi completi di controllo auto, tra cui ispezione tecnica dettagliata, controllo dello storico dei danni e verifica del chilometraggio. Il nostro partner di fiducia è a vostra disposizione.' },
    partners: [{ id: 'p-cr85-auto', name: 'CR85 Auto', description: {
      [Language.RO]: 'Servicii profesionale de verificare auto.',
      [Language.DE]: 'Professionelle Fahrzeugüberprüfungsdienste.',
      [Language.EN]: 'Professional car inspection services.',
      [Language.IT]: 'Servizi professionali di ispezione auto.',
    }, website: 'https://cr85-auto.de/', phone: '+49 15175312107',
    carCheckDetails: {
      items: [
        {
          icon: 'ShieldCheck',
          title: {
            [Language.RO]: 'Securitatea tranzacției',
            [Language.DE]: 'Sicherheit der Transaktion',
            [Language.EN]: 'Security of the transaction',
            [Language.IT]: 'Sicurezza della transazione',
          },
          description: {
            [Language.RO]: 'Verificarea mașinii pentru deficiențe ascunse și puritate juridică, ceea ce oferă protecție împotriva posibilelor înșelăciuni.',
            [Language.DE]: 'Überprüfung des Autos auf versteckte Mängel und rechtliche Reinheit, was Schutz vor möglichen Täuschungen bietet.',
            [Language.EN]: 'Checking the car for hidden deficiencies and legal purity, which provides protection against possible deception.',
            [Language.IT]: 'Controllo dell\'auto per vizi occulti e purezza legale, che fornisce protezione contro possibili inganni.',
          },
        },
        {
          icon: 'Wrench',
          title: {
            [Language.RO]: 'Examinare profesională',
            [Language.DE]: 'Professionelle Untersuchung',
            [Language.EN]: 'Professional examination',
            [Language.IT]: 'Esame professionale',
          },
          description: {
            [Language.RO]: 'Efectuăm o inspecție detaliată a mașinii, evaluăm motorul, caroseria, șasiul și oferim recomandări pentru achiziționarea acesteia, oferindu-vă informații complete despre mașină.',
            [Language.DE]: 'Wir führen eine detaillierte Inspektion des Autos durch, bewerten Motor, Karosserie, Fahrwerk und geben Empfehlungen für den Kauf, um Ihnen vollständige Informationen über das Auto zu geben.',
            [Language.EN]: 'We conduct a detailed inspection of the car, evaluate the engine, body, chassis, and give recommendations, on its purchase, providing you with complete information about the car.',
            [Language.IT]: 'Conduciamo un\'ispezione dettagliata dell\'auto, valutiamo motore, carrozzeria, telaio e diamo raccomandazioni per l\'acquisto, fornendoti informazioni complete sull\'auto.',
          },
        },
        {
          icon: 'BadgeCent',
          title: {
            [Language.RO]: 'Economii financiare',
            [Language.DE]: 'Finanzielle Einsparungen',
            [Language.EN]: 'Savings of Finance',
            [Language.IT]: 'Risparmio finanziario',
          },
          description: {
            [Language.RO]: 'Adesea, reducerea pe care o obținem de la vânzător este mai mare decât costul serviciilor noastre – ceea ce face achiziția prin noi mai profitabilă.',
            [Language.DE]: 'Oft ist der Rabatt, den wir vom Verkäufer erhalten, höher als die Kosten unserer Dienstleistungen – was den Kauf über uns rentabler macht.',
            [Language.EN]: 'Often the discount that we seek from the seller is higher than the cost of our services – which makes the purchase through us more profitable.',
            [Language.IT]: 'Spesso lo sconto che otteniamo dal venditore è superiore al costo dei nostri servizi, il che rende l\'acquisto tramite noi più redditizio.',
          },
        },
        {
          icon: 'Star',
          title: {
            [Language.RO]: 'Asigurarea calității',
            [Language.DE]: 'Qualitätssicherung',
            [Language.EN]: 'Quality assurance',
            [Language.IT]: 'Garanzia di qualità',
          },
          description: {
            [Language.RO]: 'Lucrăm doar cu mașini de încredere, oferindu-vă încredere în calitatea lor la cumpărare.',
            [Language.DE]: 'Wir arbeiten nur mit vertrauenswürdigen Autos und geben Ihnen beim Kauf Vertrauen in deren Qualität.',
            [Language.EN]: 'We only work with trusted cars, providing you with confidence in their quality when buying.',
            [Language.IT]: 'Lavoriamo solo con auto di fiducia, fornendoti fiducia nella loro qualità al momento dell\'acquisto.',
          },
        },
        {
          icon: 'Users',
          title: {
            [Language.RO]: 'Abordare individuală',
            [Language.DE]: 'Individueller Ansatz',
            [Language.EN]: 'Individual approach',
            [Language.IT]: 'Approccio individuale',
          },
          description: {
            [Language.RO]: 'Fiecare client este special. Alegem mașina conform așteptărilor dumneavoastră, astfel încât să obțineți exact rezultatul dorit.',
            [Language.DE]: 'Jeder Kunde ist etwas Besonderes. Wir wählen das Auto nach Ihren Erwartungen aus, damit Sie genau das Ergebnis erhalten, das Sie benötigen.',
            [Language.EN]: 'Every customer is special. We choose the car for your expectations so that you get exactly the result that is needed.',
            [Language.IT]: 'Ogni cliente è speciale. Scegliamo l\'auto in base alle tue aspettative in modo da ottenere esattamente il risultato necessario.',
          },
        },
        {
          icon: 'Clock',
          title: {
            [Language.RO]: 'Economie de timp',
            [Language.DE]: 'Zeitersparnis',
            [Language.EN]: 'Saving time',
            [Language.IT]: 'Risparmio di tempo',
          },
          description: {
            [Language.RO]: 'Apelarea vânzătorilor și deplasările pentru a inspecta mașinile. Ne ocupăm de întregul proces de selecție și oferim o opțiune gata pregătită.',
            [Language.DE]: 'Anrufe bei den Verkäufern und Fahrten zur Inspektion der Autos. Wir übernehmen den gesamten Auswahlprozess und bieten eine fertige Option.',
            [Language.EN]: 'Calling the sellers, and trips to inspect the cars. We take on the whole selection process and provide a ready-made option.',
            [Language.IT]: 'Chiamare i venditori e viaggi per ispezionare le auto. Ci occupiamo dell\'intero processo di selezione e forniamo un\'opzione già pronta.',
          },
        },
      ],
    }
  }],
  },
  {
    id: 'car-registration',
    iconName: 'ClipboardPaste',
    title: { [Language.RO]: 'Inregistrari auto', [Language.DE]: 'Fahrzeuganmeldungen', [Language.EN]: 'Car Registrations', [Language.IT]: 'Immatricolazioni Auto' },
    description: { [Language.RO]: 'Înmatriculare, numere de export și toate actele necesare.', [Language.DE]: 'Anmeldung, Ausfuhrkennzeichen und alle notwendigen Unterlagen.', [Language.EN]: 'Registration, export plates, and all necessary documents.', [Language.IT]: 'Immatricolazione, targhe di esportazione e tutti i documenti necessari.' },
    longDescription: { [Language.RO]: 'Ne ocupăm de întregul proces de înmatriculare a vehiculului, de la obținerea numerelor de înmatriculare temporare (export) până la înregistrarea finală. Rapid și eficient prin partenerul nostru.', [Language.DE]: 'Wir kümmern uns um den gesamten Prozess der Fahrzeuganmeldung, von der Beschaffung von temporären Ausfuhrkennzeichen bis zur endgültigen Anmeldung. Schnell und effizient durch unseren Partner.', [Language.EN]: 'We handle the entire vehicle registration process, from obtaining temporary export plates to final registration. Fast and efficient through our partner.', [Language.IT]: 'Gestiamo l\'intero processo di immatricolazione del veicolo, dall\'ottenimento di targhe di esportazione temporanee alla registrazione finale. Veloce ed efficiente tramite il nostro partner.' },
    partners: [{ id: 'p-cr85-info', name: 'CR85', description: {
      [Language.RO]: 'Servicii complete de înregistrări auto.',
      [Language.DE]: 'Komplette Dienstleistungen für die Fahrzeugregistrierung.',
      [Language.EN]: 'Complete car registration services.',
      [Language.IT]: 'Servizi completi di immatricolazione auto.',
    }, website: 'https://cr85.info/', phone: '+49 15175312107',
    registrationDetails: {
      header: {
        [Language.RO]: 'Serviciile noastre',
        [Language.DE]: 'Unsere Dienstleistungen',
        [Language.EN]: 'Our Services',
        [Language.IT]: 'I nostri servizi',
      },
      subtitle: {
        [Language.RO]: 'NUREMBERG, FÜRTH, ERLANGEN ȘI MULTE ALTELE',
        [Language.DE]: 'NÜRNBERG, FÜRTH, ERLANGEN UND VIELES MEHR',
        [Language.EN]: 'NUREMBERG, FÜRTH, ERLANGEN AND MUCH MORE',
        [Language.IT]: 'NORIMBERGA, FÜRTH, ERLANGEN E MOLTO ALTRO',
      },
      plates: [
        {
          title: {
            [Language.RO]: 'Numere de export / Plăcuțe vamale',
            [Language.DE]: 'Ausfuhrkennzeichen',
            [Language.EN]: 'Export Plates',
            [Language.IT]: 'Targhe di esportazione',
          },
          description: {
            [Language.RO]: 'Dacă doriți să vă transferați vehiculul în străinătate, obțineți de la noi plăcuțele de export.',
            [Language.DE]: 'Möchten Sie Ihr KFZ ins Ausland überführen, bekommen Sie von uns Ihr Ausfuhrkennzeichen.',
            [Language.EN]: 'If you want to transfer your vehicle abroad, you will get your export plates from us.',
            [Language.IT]: 'Se desideri trasferire il tuo veicolo all\'estero, otterrai da noi le targhe di esportazione.',
          },
        },
        {
          title: {
            [Language.RO]: 'Numere pe termen scurt / Provizorii',
            [Language.DE]: 'Kurzzeitkennzeichen',
            [Language.EN]: 'Short-term Plates',
            [Language.IT]: 'Targhe a breve termine',
          },
          description: {
            [Language.RO]: 'Pentru test drive-uri și transferuri, vă procurăm plăcuțele de înmatriculare provizorii.',
            [Language.DE]: 'Für Probe- und Überführungsfahrten besorgen wir Ihnen Ihr Kurzzeitkennzeichen.',
            [Language.EN]: 'For test drives and transfers, we will get you your short-term plates.',
            [Language.IT]: 'Per test drive e trasferimenti, ti procuriamo le targhe a breve termine.',
          },
        },
        {
          title: {
            [Language.RO]: 'Înmatriculare și Radiere Auto',
            [Language.DE]: 'KFZ An- und Abmeldung',
            [Language.EN]: 'Vehicle Registration and Deregistration',
            [Language.IT]: 'Immatricolazione e radiazione veicolo',
          },
          description: {
            [Language.RO]: 'La noi vă puteți înregistra și dereglementa rapid și ușor autovehiculul (KFZ).',
            [Language.DE]: 'Bei uns können Sie problemlos und schnell Ihr Kraftfahrzeug (KFZ) anmelden und auch abmelden.',
            [Language.EN]: 'With us, you can easily and quickly register and deregister your motor vehicle (KFZ).',
            [Language.IT]: 'Da noi puoi registrare e radiare facilmente e rapidamente il tuo veicolo (KFZ).',
          },
        },
        {
          title: {
            [Language.RO]: 'Numere pentru vehicule Electrice (E-Kennzeichen)',
            [Language.DE]: 'E-Kennzeichen (Elektro)',
            [Language.EN]: 'E-Plates (Electric)',
            [Language.IT]: 'Targhe E (elettriche)',
          },
          description: {
            [Language.RO]: 'De asemenea, putem înregistra și dereglementa vehiculele electrice pentru dumneavoastră.',
            [Language.DE]: 'Elektrofahrzeuge können wir für Sie ebenfalls an- und abmelden.',
            [Language.EN]: 'We can also register and deregister electric vehicles for you.',
            [Language.IT]: 'Possiamo anche registrare e radiare i vechiculele electrice pentru dumneavoastră.',
          },
        },
        {
          title: {
            [Language.RO]: 'Numere istorice / Oldtimer (H-Kennzeichen)',
            [Language.DE]: 'H-Kennzeichen (Oldtimer)',
            [Language.EN]: 'H-Plates (Classic Cars)',
            [Language.IT]: 'Targhe H (auto d\'epoca)',
          },
          description: {
            [Language.RO]: 'Cu plăcere vă eliberăm o plăcuță H pentru vehiculul dumneavoastră de epocă.',
            [Language.DE]: 'Gerne stellen wir Ihnen für Ihren Oldtimer ein H-Kennzeichen aus.',
            [Language.EN]: 'We would be happy to issue an H-plate for your classic car.',
            [Language.IT]: 'Siamo lieti di rilasciarti o targa H pentru vehiculul dumneavoastră de epocă.',
          },
        },
        {
          title: {
            [Language.RO]: 'Numele sezoniere',
            [Language.DE]: 'Saisonkennzeichen',
            [Language.EN]: 'Seasonal Plates',
            [Language.IT]: 'Targhe stagionale',
          },
          description: {
            [Language.RO]: 'La cerere, vă înregistrăm vehiculul doar sezonier (de exemplu, din aprilie până în octombrie).',
            [Language.DE]: 'Wir melden Ihr KFZ auf Wunsch auch nur saisonal an (beispielsweise von April bis Oktober)',
            [Language.EN]: 'Upon request, we will also register your vehicle seasonally (for example, from April to October).',
            [Language.IT]: 'Su richiesta, registreremo il tuo veicolo solo sezonier (de exemplu, din aprilie până în octombrie).',
          },
        },
      ],
    },
    website: 'https://cr85.info/', phone: '+49 15175312107' }],
  },
  {
    id: 'tax-consulting',
    iconName: 'Landmark',
    title: { [Language.RO]: 'Steuerberater, Consiliere fiscala si recalculare de taxe', [Language.DE]: 'Steuerberater, Steuerberatung und Steuerneuberechnung', [Language.EN]: 'Tax Advisor, Tax Counseling and Tax Recalculation', [Language.IT]: 'Consulente Fiscale, Consulenza Fiscale e Ricalcolo Fiscale' },
    description: { [Language.RO]: 'Consultanță fiscală specializată pentru optimizarea taxelor.', [Language.DE]: 'Spezialisierte Steuerberatung zur Steueroptimierung.', [Language.EN]: 'Specialized tax consulting for tax optimization.', [Language.IT]: 'Consulenza fiscale specializzata per l\'ottimizzazione fiscale.' },
    longDescription: {
      [Language.RO]: 'Prin biroul nostru aveti posibilitatea de a beneficia de unul dintre cei mai buni Contabili cat si de cunostintele noastre atat pentru persoane fizice cat si pentru firme !',
      [Language.DE]: 'Durch unser Büro haben Sie die Möglichkeit, von einem der besten Buchhalter sowie unserem Wissen für Privatpersonen und Unternehmen zu profitieren!',
      [Language.EN]: 'Through our office you have the opportunity to benefit from one of the best Accountants as well as our knowledge for both individuals and companies!',
      [Language.IT]: 'Attraverso il nostro ufficio hai l\'opportunità di beneficiare di uno dei migliori commercialisti e della nostra conoscenza sia per i privati che per le aziende!',
    },
    partners: [tudoseAlexandruFinanz],
  },
  {
    id: 'insurance',
    iconName: 'ShieldCheck',
    title: { [Language.RO]: 'Asigurări', [Language.DE]: 'Versicherungen', [Language.EN]: 'Insurance', [Language.IT]: 'Assicurazioni' },
    description: { [Language.RO]: 'Auto, viață, sănătate și bunuri.', [Language.DE]: 'Auto, Leben, Gesundheit und Eigentum.', [Language.EN]: 'Auto, life, health, and property.', [Language.IT]: 'Auto, vita, salute e proprietà.' },
    longDescription: {
      [Language.RO]: 'Nu va putem garanta cele mai ieftine asigurari dar va putem asigura de cea mai buna calitate in raport cu piata actuala !',
      [Language.DE]: 'Wir können Ihnen nicht die günstigsten Versicherungen garantieren, aber wir können Ihnen die beste Qualität im Verhältnis zum aktuellen Markt sichern!',
      [Language.EN]: 'We cannot guarantee you the cheapest insurance, but we can assure you of the best quality in relation to the current market!',
      [Language.IT]: 'Non possiamo garantirvi l\'assicurazione più economica, ma possiamo assicurarvi la migliore qualità in relazione al mercato attuale!',
    },
    partners: [tudoseAlexandruFinanz],
  },
  {
    id: 'loans-financing',
    iconName: 'Banknote',
    title: { [Language.RO]: 'Credite, Finantari auto sau imobiliare si inchideri anticipate', [Language.DE]: 'Kredite, Auto- oder Immobilienfinanzierung und vorzeitige Schließungen', [Language.EN]: 'Loans, Car or Real Estate Financing and Early Closures', [Language.IT]: 'Prestiti, Finanziamenti Auto o Immobiliari e Chiusure Anticipate' },
    description: { [Language.RO]: 'Soluții de finanțare flexibile pentru planurile tale.', [Language.DE]: 'Flexible Finanzierungslösungen für Ihre Pläne.', [Language.EN]: 'Flexible financing solutions for your plans.', [Language.IT]: 'Soluzioni di finanziamento flessibili per i tuoi piani.' },
    longDescription: {
      [Language.RO]: 'Va suntem alaturi atat pentru credite de nevoi personale cat si pentru refinantarea unuia activ. Va sprijinim pentru finantarea unui automobil sau a unei case cat si creerea unui plan si a unei strategii astfel incat plata sa poata fi mai rapida !',
      [Language.DE]: 'Wir stehen Ihnen sowohl bei Privatkrediten als auch bei der Refinanzierung eines aktiven Kredits zur Seite. Wir unterstützen Sie bei der Finanzierung eines Autos oder Hauses sowie bei der Erstellung eines Plans und einer Strategie, damit die Zahlung schneller erfolgen kann!',
      [Language.EN]: 'We are with you for both personal loans and for refinancing an active one. We support you for financing a car or a house as well as creating a plan and a strategy so that the payment can be faster!',
      [Language.IT]: 'Siamo con te sia per i prestiti personali che per il rifinanziamento di uno attivo. Ti supportiamo per il finanziamento di un\'auto o di una casa oltre a creare un piano e una strategia in modo che il pagamento possa essere più veloce!',
    },
    partners: [tudoseAlexandruFinanz],
  },

  {
    id: 'translations',
    iconName: 'Languages',
    title: { [Language.RO]: 'Traduceri Legalizate', [Language.DE]: 'Beglaubigte Übersetzungen', [Language.EN]: 'Legalized Translations', [Language.IT]: 'Traduzioni Legalizzate' },
    description: { [Language.RO]: 'Documente oficiale și acte auto.', [Language.DE]: 'Offizielle Dokumente und Autopapiere.', [Language.EN]: 'Official documents and car papers.', [Language.IT]: 'Documenti ufficiali e documenti auto.' },
    longDescription: {
      [Language.RO]: 'Va putem sta la dispozitie cu traduceri legalizate in 35 de limbi in maxim 24/48 de ore in functie de complexitate !',
      [Language.DE]: 'Wir können Ihnen beglaubigte Übersetzungen in 35 Sprachen innerhalb von maximal 24/48 Stunden je nach Komplexität zur Verfügung stellen!',
      [Language.EN]: 'We can provide you with legalized translations in 35 languages within a maximum of 24/48 hours depending on the complexity!',
      [Language.IT]: 'Possiamo fornirvi traduzioni legalizzate in 35 lingue in un massimo di 24/48 ore a seconda della complessità!',
    },
    partners: [tudoseAlexandruFinanz],
  },
  {
    id: 'schufa-help',
    iconName: 'Eraser',
    title: { [Language.RO]: 'Ajutor si sprijin cu scor Schufa scazut', [Language.DE]: 'Hilfe und Unterstützung bei niedrigem Schufa-Score', [Language.EN]: 'Help and support with a low Schufa score', [Language.IT]: 'Aiuto e supporto con un punteggio Schufa basso' },
    description: { [Language.RO]: 'Consultanță pentru rectificarea scorului.', [Language.DE]: 'Beratung zur Score-Korrektur.', [Language.EN]: 'Consulting for score rectification.', [Language.IT]: 'Consulenza per la rettifica del punteggio.' },
    longDescription: {
      [Language.RO]: 'Pentru clientii nostri activi oferim sfaturi si ajutor in revizuirea scorului Schufa !',
      [Language.DE]: 'Für unsere aktiven Kunden bieten wir Beratung und Hilfe bei der Überprüfung des Schufa-Scores!',
      [Language.EN]: 'For our active clients we offer advice and help in reviewing the Schufa score!',
      [Language.IT]: 'Per i nostri clienti attivi offriamo consulenza e aiuto nella revisione del punteggio Schufa!',
    },
    partners: [tudoseAlexandruFinanz],
  },
];